/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewNodeDialog.java
 *
 * Created on 24-feb-2010, 14.49.56
 */

package simpleConfigurationPanel;

import ie.ucd.clarity.bmf.network.manager.*;
import ie.ucd.clarity.bmf.common.Constants;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class DestinationDialog extends javax.swing.JDialog {

    /** Creates new form NewNodeDialog */
    public DestinationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodeJLabel = new javax.swing.JLabel();
        destinationJPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        destinationFormulaJTextArea = new javax.swing.JTextArea();
        resetDestinationFormnulaJButton = new javax.swing.JButton();
        OKJButton1 = new javax.swing.JButton();
        cancelJButton1 = new javax.swing.JButton();
        destinationBroadcastNode1 = new javax.swing.JButton();
        destinationAddSelectedNode = new javax.swing.JButton();
        operatorIntersectionJButton = new javax.swing.JButton();
        operatorUnionJButton = new javax.swing.JButton();
        operatorJLabel = new javax.swing.JLabel();
        destinationAddSelectedGroup = new javax.swing.JButton();
        destinationFormulaJLabel = new javax.swing.JLabel();
        operatorNotJButton = new javax.swing.JButton();
        nodesJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nodesJList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        groupsJList = new javax.swing.JList();
        groupsJLabel = new javax.swing.JLabel();
        destinationHelpJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Destination");
        setAlwaysOnTop(true);

        nodeJLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        nodeJLabel.setText("DESTINATION");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        destinationFormulaJTextArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        destinationFormulaJTextArea.setColumns(20);
        destinationFormulaJTextArea.setEditable(false);
        destinationFormulaJTextArea.setFont(new java.awt.Font("Tahoma", 0, 12));
        destinationFormulaJTextArea.setLineWrap(true);
        destinationFormulaJTextArea.setRows(3);
        destinationFormulaJTextArea.setTabSize(3);
        destinationFormulaJTextArea.setText("\"Ambiental Light\" \nU \"Light State\"");
        destinationFormulaJTextArea.setWrapStyleWord(true);
        destinationFormulaJTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(destinationFormulaJTextArea);

        resetDestinationFormnulaJButton.setText("Reset Destination Formula");
        resetDestinationFormnulaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDestinationFormnulaJButtonActionPerformed(evt);
            }
        });

        OKJButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        OKJButton1.setIcon((new GetIcon()).getOKIcon());
        OKJButton1.setText("");
        OKJButton1.setToolTipText("OK");
        OKJButton1.setBorder(null);
        OKJButton1.setBorderPainted(false);
        OKJButton1.setContentAreaFilled(false);
        OKJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKJButton1ActionPerformed(evt);
            }
        });

        cancelJButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        cancelJButton1.setIcon((new GetIcon()).getCancelIcon());
        cancelJButton1.setText("");
        cancelJButton1.setToolTipText("CANCEL");
        cancelJButton1.setBorder(null);
        cancelJButton1.setBorderPainted(false);
        cancelJButton1.setContentAreaFilled(false);
        cancelJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButton1ActionPerformed(evt);
            }
        });

        destinationBroadcastNode1.setText("Add All Nodes");
        destinationBroadcastNode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationBroadcastNode1ActionPerformed(evt);
            }
        });

        destinationAddSelectedNode.setText("Add Node");
        destinationAddSelectedNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationAddSelectedNodeActionPerformed(evt);
            }
        });

        operatorIntersectionJButton.setText("∩");
        operatorIntersectionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorIntersectionJButtonActionPerformed(evt);
            }
        });

        operatorUnionJButton.setText("∪");
        operatorUnionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorUnionJButtonActionPerformed(evt);
            }
        });

        operatorJLabel.setText("GROUP OPERATORS");

        destinationAddSelectedGroup.setText("Add Group");
        destinationAddSelectedGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationAddSelectedGroupActionPerformed(evt);
            }
        });

        destinationFormulaJLabel.setText("DESTINATION FORMULA");

        operatorNotJButton.setText("!");
        operatorNotJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorNotJButtonActionPerformed(evt);
            }
        });

        nodesJLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        nodesJLabel.setText("NODES");

        nodesJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Node 1", "Node 2", "Node 3", "Node 4", "Node 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        nodesJList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(nodesJList);

        groupsJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Ambiental Light", "Light State", "Presence Detector" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        groupsJList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(groupsJList);

        groupsJLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        groupsJLabel.setText("GROUPS");

        javax.swing.GroupLayout destinationJPanelLayout = new javax.swing.GroupLayout(destinationJPanel);
        destinationJPanel.setLayout(destinationJPanelLayout);
        destinationJPanelLayout.setHorizontalGroup(
            destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destinationJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(destinationJPanelLayout.createSequentialGroup()
                            .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nodesJLabel)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(destinationAddSelectedNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destinationBroadcastNode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(51, 51, 51)
                            .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(destinationJPanelLayout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(operatorNotJButton)
                                        .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(destinationJPanelLayout.createSequentialGroup()
                                                .addComponent(operatorUnionJButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(operatorIntersectionJButton))
                                            .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(operatorJLabel)
                                                .addComponent(destinationAddSelectedGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))))
                                .addComponent(groupsJLabel))
                            .addGap(29, 29, 29))
                        .addGroup(destinationJPanelLayout.createSequentialGroup()
                            .addComponent(destinationFormulaJLabel)
                            .addContainerGap(408, Short.MAX_VALUE))
                        .addGroup(destinationJPanelLayout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(358, Short.MAX_VALUE))
                        .addGroup(destinationJPanelLayout.createSequentialGroup()
                            .addComponent(resetDestinationFormnulaJButton)
                            .addContainerGap(368, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, destinationJPanelLayout.createSequentialGroup()
                        .addComponent(cancelJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OKJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        destinationJPanelLayout.setVerticalGroup(
            destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destinationJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodesJLabel)
                    .addComponent(groupsJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(destinationJPanelLayout.createSequentialGroup()
                        .addComponent(destinationAddSelectedGroup)
                        .addGap(18, 18, 18)
                        .addComponent(operatorJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(operatorUnionJButton)
                            .addComponent(operatorIntersectionJButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(operatorNotJButton))
                    .addGroup(destinationJPanelLayout.createSequentialGroup()
                        .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(destinationJPanelLayout.createSequentialGroup()
                                .addComponent(destinationBroadcastNode1)
                                .addGap(18, 18, 18)
                                .addComponent(destinationAddSelectedNode))
                            .addGroup(destinationJPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(destinationFormulaJLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(destinationJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetDestinationFormnulaJButton)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(destinationJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(destinationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OKJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        destinationHelpJButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        destinationHelpJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmf/images/InfoSmall.png"))); // NOI18N
        destinationHelpJButton.setBorder(null);
        destinationHelpJButton.setBorderPainted(false);
        destinationHelpJButton.setContentAreaFilled(false);
        destinationHelpJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        destinationHelpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationHelpJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nodeJLabel)
                .addGap(18, 18, 18)
                .addComponent(destinationHelpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(destinationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(destinationHelpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nodeJLabel))
                .addContainerGap(407, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(destinationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKJButton1ActionPerformed
        dad.destinationChanged(destinationFormulaToShow, destinationFormulaToElaborate, isDestinationFormulaNode, waiting4GroupInDestinationFormula);
        this.dispose();
}//GEN-LAST:event_OKJButton1ActionPerformed

    private void destinationHelpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationHelpJButtonActionPerformed
        DestinationHelpDialog dialog = new DestinationHelpDialog(new javax.swing.JFrame(), true);

        dialog.setVisible(true);
}//GEN-LAST:event_destinationHelpJButtonActionPerformed

    private void destinationBroadcastNode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationBroadcastNode1ActionPerformed
        resetDestinationFormula();
        this.isDestinationFormulaNode = true;

        destinationFormulaToShow="ALL NODES";
        destinationFormulaToElaborate=""+ Constants.ADDRESSEE_BROADCAST;
        this.destinationFormulaJTextArea.setText(destinationFormulaToShow);

        //updateDestinationFormulasInAllTabs();
}//GEN-LAST:event_destinationBroadcastNode1ActionPerformed

    private void destinationAddSelectedNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationAddSelectedNodeActionPerformed
        resetDestinationFormula();
        this.isDestinationFormulaNode = true;

        BMFNode nodeTemp = (BMFNode)this.nodesJList.getSelectedValue();

        if(nodeTemp != null){
            destinationFormulaToShow=""+nodeTemp;
            destinationFormulaToElaborate=""+nodeTemp.getNodeID();
            this.destinationFormulaJTextArea.setText(destinationFormulaToShow);
            //updateDestinationFormulasInAllTabs();
        }
        else JOptionPane.showMessageDialog(this, "No Node Selected!");
    }//GEN-LAST:event_destinationAddSelectedNodeActionPerformed

    private void destinationAddSelectedGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationAddSelectedGroupActionPerformed
        if(this.isDestinationFormulaNode){
            this.isDestinationFormulaNode = false;
            resetDestinationFormula();
        }

        BMFGroup groupTemp = (BMFGroup)this.groupsJList.getSelectedValue();

        if(groupTemp != null){
            if(waiting4GroupInDestinationFormula){
                destinationFormulaToShow+="\""+groupTemp + "\"\n";
                destinationFormulaToElaborate+=""+groupTemp.getGroupID();
                this.destinationFormulaJTextArea.setText(destinationFormulaToShow);
                //updateDestinationFormulasInAllTabs();
                waiting4GroupInDestinationFormula = false;
            }
            else JOptionPane.showMessageDialog(this, "Union or Intersection Expected! No Group or Negation Allowed Here!");
            

        }
        else JOptionPane.showMessageDialog(this, "No Group Selected!");
}//GEN-LAST:event_destinationAddSelectedGroupActionPerformed

    private void operatorUnionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorUnionJButtonActionPerformed
        if(this.isDestinationFormulaNode){
            this.isDestinationFormulaNode = false;
            resetDestinationFormula();
        }
        if(!waiting4GroupInDestinationFormula){
            destinationFormulaToShow+="UNION ";
            destinationFormulaToElaborate+="|";
            this.destinationFormulaJTextArea.setText(destinationFormulaToShow);
            //updateDestinationFormulasInAllTabs();
            waiting4GroupInDestinationFormula = true;
        }
        else JOptionPane.showMessageDialog(this, "Group or Negation Expected! No Union or Intersection Allowed Here!");
    }//GEN-LAST:event_operatorUnionJButtonActionPerformed

    private void operatorIntersectionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorIntersectionJButtonActionPerformed
        if(this.isDestinationFormulaNode){
            this.isDestinationFormulaNode = false;
            resetDestinationFormula();
        }
        if(!waiting4GroupInDestinationFormula){
            destinationFormulaToShow+="INTERSECTION ";
            destinationFormulaToElaborate+="&";
            this.destinationFormulaJTextArea.setText(destinationFormulaToShow);
            //updateDestinationFormulasInAllTabs();
            waiting4GroupInDestinationFormula = true;
        }
        else JOptionPane.showMessageDialog(this, "Group or Negation Expected! No Union or Intersection Allowed Here!");
}//GEN-LAST:event_operatorIntersectionJButtonActionPerformed

    private void operatorNotJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorNotJButtonActionPerformed
        if(this.isDestinationFormulaNode){
            this.isDestinationFormulaNode = false;
            resetDestinationFormula();
        }
        if(waiting4GroupInDestinationFormula){
            if(destinationFormulaToElaborate.endsWith("!")){
                JOptionPane.showMessageDialog(this, "No double negation allowed!");
                return;
            }
            destinationFormulaToShow+="! ";
            destinationFormulaToElaborate+="!";
            this.destinationFormulaJTextArea.setText(destinationFormulaToShow);
            //updateDestinationFormulasInAllTabs();
            waiting4GroupInDestinationFormula = true;
        }
        else JOptionPane.showMessageDialog(this, "Union or Intersection Expected! No Group or Negation Allowed Here!");
}//GEN-LAST:event_operatorNotJButtonActionPerformed

    private void resetDestinationFormnulaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDestinationFormnulaJButtonActionPerformed
        int ret = JOptionPane.showConfirmDialog (this, "Do you want to reset the current Destination Formula?",
                                                 "Select please", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (ret == JOptionPane.YES_OPTION){
            resetDestinationFormula();
        }


    }//GEN-LAST:event_resetDestinationFormnulaJButtonActionPerformed

    private void cancelJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButton1ActionPerformed
        this.dispose();
}//GEN-LAST:event_cancelJButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DestinationDialog dialog = new DestinationDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKJButton1;
    private javax.swing.JButton cancelJButton1;
    private javax.swing.JButton destinationAddSelectedGroup;
    private javax.swing.JButton destinationAddSelectedNode;
    private javax.swing.JButton destinationBroadcastNode1;
    private javax.swing.JLabel destinationFormulaJLabel;
    private javax.swing.JTextArea destinationFormulaJTextArea;
    private javax.swing.JButton destinationHelpJButton;
    private javax.swing.JPanel destinationJPanel;
    private javax.swing.JLabel groupsJLabel;
    private javax.swing.JList groupsJList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nodeJLabel;
    private javax.swing.JLabel nodesJLabel;
    private javax.swing.JList nodesJList;
    private javax.swing.JButton operatorIntersectionJButton;
    private javax.swing.JLabel operatorJLabel;
    private javax.swing.JButton operatorNotJButton;
    private javax.swing.JButton operatorUnionJButton;
    private javax.swing.JButton resetDestinationFormnulaJButton;
    // End of variables declaration//GEN-END:variables

  
    GUIFrame dad;

    private String destinationFormulaToShow="";
    private String destinationFormulaToElaborate="";
    private boolean isDestinationFormulaNode=true;
    private boolean waiting4GroupInDestinationFormula=true;


    public void setDadAndPopulateFields(GUIFrame dad){
        this.dad=dad;

        populateJLists();

        this.destinationFormulaToShow = dad.destinationFormulaToShow;
        this.destinationFormulaToElaborate = dad.destinationFormulaToElaborate;
        this.isDestinationFormulaNode = dad.isDestinationFormulaNode;
        this.waiting4GroupInDestinationFormula = dad.waiting4GroupInDestinationFormula;
        this.destinationFormulaJTextArea.setText(destinationFormulaToShow);
        
        //resetDestinationFormula();
    }

    private void resetDestinationFormula(){
        destinationFormulaToShow="";
        destinationFormulaToElaborate="";
        this.destinationFormulaJTextArea.setText("");
        //updateDestinationFormulasInAllTabs();
        waiting4GroupInDestinationFormula = true;
    }

    private void populateJLists() {
        groupsJList.setListData(dad.BMFGroupVector);
        nodesJList.setListData(dad.BMFNodeVector);
    }

}
