/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewNodeDialog.java
 *
 * Created on 24-feb-2010, 14.49.56
 */

package simpleConfigurationPanel;

/**
 *
 * @author Antonio
 */
public class NewGroupDialog extends javax.swing.JDialog {

    /** Creates new form NewNodeDialog */
    public NewGroupDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newGroupNameJTextField = new javax.swing.JTextField();
        cancelJButton1 = new javax.swing.JButton();
        OKJButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NEW GROUP");
        setAlwaysOnTop(true);

        jLabel1.setText("Type the NEW GROUP name");

        newGroupNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGroupNameJTextFieldActionPerformed(evt);
            }
        });
        newGroupNameJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newGroupNameJTextFieldKeyTyped(evt);
            }
        });

        cancelJButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        cancelJButton1.setIcon((new GetIcon()).getCancelIcon());
        cancelJButton1.setText("");
        cancelJButton1.setToolTipText("CANCEL");
        cancelJButton1.setBorder(null);
        cancelJButton1.setBorderPainted(false);
        cancelJButton1.setContentAreaFilled(false);
        cancelJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButton1ActionPerformed(evt);
            }
        });

        OKJButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        OKJButton1.setIcon((new GetIcon()).getOKIcon());
        OKJButton1.setText("");
        OKJButton1.setToolTipText("OK");
        OKJButton1.setBorder(null);
        OKJButton1.setBorderPainted(false);
        OKJButton1.setContentAreaFilled(false);
        OKJButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(newGroupNameJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addComponent(cancelJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OKJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newGroupNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OKJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGroupNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGroupNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newGroupNameJTextFieldActionPerformed

    private void cancelJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButton1ActionPerformed
        this.dispose();
}//GEN-LAST:event_cancelJButton1ActionPerformed

    private void OKJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKJButton1ActionPerformed
        executeOKAction();


}//GEN-LAST:event_OKJButton1ActionPerformed

    private void newGroupNameJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newGroupNameJTextFieldKeyTyped
        if(evt.getKeyChar()==evt.VK_ENTER){
            executeOKAction();
        }
    }//GEN-LAST:event_newGroupNameJTextFieldKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewGroupDialog dialog = new NewGroupDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKJButton1;
    private javax.swing.JButton cancelJButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField newGroupNameJTextField;
    // End of variables declaration//GEN-END:variables


    GUIFrame dad;

    public void setDad(GUIFrame dad){
        this.dad = dad;
    }

    private void executeOKAction(){
        if(this.newGroupNameJTextField.getText().length() != 0){
            dad.newGroupCreated(this.newGroupNameJTextField.getText());
            this.dispose();
        }
    }

}
