/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChartsFrame.java
 *
 * Created on 3-set-2010, 15.29.10
 */

package ie.ucd.clarity.bmf.GUI;

import java.awt.GridLayout;
import javax.swing.GroupLayout;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Andrea
 */
public class ChartsFrame extends javax.swing.JFrame {

    /** Creates new form ChartsFrame */
    public ChartsFrame() {
        initComponents();    
        this.setTitle("CHARTS");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 5));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void addGraph(ChartInternalFrame fc){
        getContentPane().add(fc);
    }


}
