/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CSVReaderFrame.java
 *
 * Created on 27-set-2010, 17.23.55
 */
package ie.ucd.clarity.bmf.GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrea
 */
public class CSVReaderFrame extends javax.swing.JFrame {

    private FileReader csvreader;
    private HashMap<String, String> configurationData;
    private String filePath;
    String[] columnname;
    Object[][] object;

    /** Creates new form CSVReaderFrame */
    public CSVReaderFrame() {
    }

    public CSVReaderFrame(String filePath) {
        this.filePath = filePath;
        try {
            this.csvreader = new FileReader(filePath);
            BufferedReader br = new BufferedReader(csvreader);
            String name = br.readLine();
            StringTokenizer st = new StringTokenizer(name, ";");
            columnname = new String[st.countTokens()];
            int i = 0;
            while (st.hasMoreTokens()) {
                columnname[i] = st.nextToken();
                i++;
            }
            object = new Object[100][columnname.length];
            String line = "";
            int j = 0;
            while ((line = br.readLine()) != null) {
                st = new StringTokenizer(line, ";");
                i = 0;
                while (st.hasMoreTokens()) {
                    object[j][i] = st.nextToken();
                    i++;
                }
                j++;
            }
        } catch (IOException ex) {
            Logger.getLogger(CSVReaderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        jTable1.setModel(new TableModel());
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    class TableModel extends DefaultTableModel {

        public TableModel() {
            super(object, columnname);
        }
        
    }
}
