/*
 * TestFomuleAboutBox.java
 */

package ie.ucd.clarity.bmf.GUI;

import ie.ucd.clarity.bmf.GUI.common.BMFGroupGUI;
import java.awt.Frame;
//import org.jdesktop.application.Action;

/**
 * @author  Matthew
 */
public class GroupDetailDialog extends javax.swing.JDialog {

    /**
	 * @uml.property  name="group"
	 * @uml.associationEnd  
	 */
    private BMFGroupGUI group;

    public GroupDetailDialog(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }

    public GroupDetailDialog(InitialFrame owner, BMFGroupGUI group) {
       super(owner);
        this.group = group;
        initComponents();
        getRootPane().setDefaultButton(closeButton);
    }  


   public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        javax.swing.JLabel titleLabel = new javax.swing.JLabel();
        javax.swing.JLabel versionLabel = new javax.swing.JLabel();
        javax.swing.JLabel idLabel = new javax.swing.JLabel();
        javax.swing.JLabel homepageLabel = new javax.swing.JLabel();
        javax.swing.JLabel groupsLabel = new javax.swing.JLabel();
        javax.swing.JLabel versionLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel idLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(group.getName());
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

    //    javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(GroupDetailDialog.class, this);
      //  closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setText("Close");
        closeButton.setName("closeButton"); // NOI18N

        titleLabel.setFont(titleLabel.getFont().deriveFont(titleLabel.getFont().getStyle() | java.awt.Font.BOLD, titleLabel.getFont().getSize()+8));
        titleLabel.setText(group.getName()+" Details");
        titleLabel.setName("titleLabel"); // NOI18N

        versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD, versionLabel.getFont().getSize()+2));
        versionLabel.setText("Group Name:");
        versionLabel.setName("versionLabel"); // NOI18N

        idLabel.setText(group.getName());
        idLabel.setName("idLabel"); // NOI18N

        homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD, homepageLabel.getFont().getSize()+2));
        homepageLabel.setText("Nodes affiliation:");
        homepageLabel.setName("homepageLabel"); // NOI18N

        groupsLabel.setText(getNodesString());
        groupsLabel.setName("groupsLabel"); // NOI18N

        versionLabel1.setFont(versionLabel1.getFont().deriveFont(versionLabel1.getFont().getStyle() | java.awt.Font.BOLD, versionLabel1.getFont().getSize()+2));
        versionLabel1.setText("Group ID:");
        versionLabel1.setName("versionLabel1"); // NOI18N

        idLabel1.setText(group.getID()+"");
        idLabel1.setName("idLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(versionLabel1)
                            .addComponent(versionLabel)
                            .addComponent(homepageLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel)
                            .addComponent(idLabel1)
                            .addComponent(groupsLabel))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(versionLabel1)
                            .addComponent(idLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(versionLabel)
                            .addComponent(idLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homepageLabel))
                    .addComponent(groupsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    // End of variables declaration//GEN-END:variables


    // End of variables declaration


    public String getNodesString(){
        String s="";
        if(group.getNodes().size()==0){
            s+="The group '"+group.getName()+"' is empty!";
        }
        for(int i=0; i<group.getNodes().size(); i++){
            if(i==group.getNodes().size()-1){
                s+=group.getNodes().get(i).getName()+".";
            }else s+=group.getNodes().get(i).getName()+", ";
        }
        return s;
    }
}
