/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RequestsFrame.java
 *
 * Created on 25-ago-2010, 17.17.32
 */
package ie.ucd.clarity.bmf.GUI;

import javax.swing.DefaultComboBoxModel;

import ie.ucd.clarity.bmf.GUI.common.BMFObjectGUI;
import org.jfree.ui.RefineryUtilities;

/**
 * @author  Andrea
 */
public class RequestsFrame extends javax.swing.JFrame {

    /**
	 * @uml.property  name="node"
	 * @uml.associationEnd  
	 */
    BMFObjectGUI node;
    /**
	 * @uml.property  name="frame"
	 * @uml.associationEnd  
	 */
    InitialFrame frame;
    boolean first=true;

    /** Creates new form RequestsFrame */
    public RequestsFrame() {
    }

    public RequestsFrame(BMFObjectGUI node, InitialFrame frame) {
        /*this.node = node;
        this.frame = frame;
        initComponents();
        RefineryUtilities.centerFrameOnScreen(this);*/
    }

    public RequestsFrame(BMFObjectGUI node) {
    }

    public void showGUI(BMFObjectGUI node, InitialFrame frame) {
        this.node = node;
        this.frame = frame;
        if (first) {
            initComponents();
            first=false;
            
        }
        scheduleRequestPanel1.setNode(this.node);
        scheduleRequestPanel1.repaint();
        RefineryUtilities.centerFrameOnScreen(this);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scheduleRequestPanel1 = new ie.ucd.clarity.bmf.GUI.components.ScheduleRequestPanel(node, frame);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Request");
        setAlwaysOnTop(true);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scheduleRequestPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scheduleRequestPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
	 * @uml.property  name="scheduleRequestPanel1"
	 * @uml.associationEnd  
	 */
    private ie.ucd.clarity.bmf.GUI.components.ScheduleRequestPanel scheduleRequestPanel1;
    // End of variables declaration//GEN-END:variables
}
