/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SingleRequestDetailsFrame.java
 *
 * Created on 6-dic-2010, 17.34.44
 */

package ie.ucd.clarity.bmf.GUI;

import ie.ucd.clarity.bmf.GUI.common.BMFRequestObjectGUI;
import org.jfree.ui.RefineryUtilities;

/**
 * @author  Andrea
 */
public class SingleRequestDetailsFrame extends javax.swing.JFrame {

    /** Creates new form SingleRequestDetailsFrame */
    public SingleRequestDetailsFrame() {
        
    }

    public SingleRequestDetailsFrame(BMFRequestObjectGUI request) {
        initComponents();
        RefineryUtilities.centerFrameOnScreen(this);
        this.setTitle(request.getName()+" DETAILS");
        detailRequestPanel1.setParameterAndShow(request);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailRequestPanel1 = new ie.ucd.clarity.bmf.GUI.DetailRequestPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        detailRequestPanel1.setName("detailRequestPanel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailRequestPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailRequestPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingleRequestDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
	 * @uml.property  name="detailRequestPanel1"
	 * @uml.associationEnd  
	 */
    private ie.ucd.clarity.bmf.GUI.DetailRequestPanel detailRequestPanel1;
    // End of variables declaration//GEN-END:variables

}
